routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get ( '/redirect/{service}', 'Auth\RegisterController@redirect' );
Route::get ( '/callback/{service}', 'Auth\RegisterController@callback' );

Route::group(['prefix' => LaravelLocalization::setLocale() ], function()
{
    Route::post('register' , 'Auth\RegisterController@register');
    // login
    Route::post('loginUser' , 'Auth\LoginController@loginUser');
});


//-------------------------------------------------------------------//
//--------------------------ADMIN PANEL------------------------------//
//-------------------------------------------------------------------//

Route::group(['prefix' => LaravelLocalization::setLocale(),'middleware'=>['localeSessionRedirect', 'localizationRedirect', 'localeViewPath','web']],function() {
    
   Route::get('/', 'HomeController@index')->name('homepage');

   Route::get('/register', 'HomeController@register');
   Route::post('/registerform','HomeController@registerform');

   Route::get('loginpage','HomeController@loginpage');
   Route::post('loginform','HomeController@loginform');


   Route::get('/user_ads/{id}', 'HomeController@user_ads')->name('myadv');
   Route::get('/Favorits_ads', 'HomeController@Favorits_ads');
   Route::get('/category', 'HomeController@category');
   Route::get('/ad_details/{id}', 'HomeController@ad_details');

   Route::get('/advpage','HomeController@advpage');
   Route::post('/addadvert','HomeController@addadvert');

   Route::post('/contactus','HomeController@contactus');

   Route::get('/catadverts', 'HomeController@catadverts');

   Route::get('/catadvertsdetails/{id}','HomeController@catadvertsdetails');
   

   Route::post('/searchresult','HomeController@searchresult');
   


} );

  //-------------------------------------------------------------------//
 //--------------------------ADMIN PANEL------------------------------//
//-------------------------------------------------------------------//

Route::group(['prefix' => LaravelLocalization::setLocale(),'middleware'=>['localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ,'admin']],function() {

    Route::get('/adminPanel','backend\DashboardController@index')->name('adminPanel');


    Route::resource('languages','backend\LanguagesController');

    Route::resource('departments','backend\DepartmentsController');

    Route::post('add_sub/{id}','backend\DepartmentsController@addSub')->name('add_sub');
    Route::post('store_sub/{id}','backend\DepartmentsController@storeSub')->name('store_sub');

    Route::get('show_subs/{id}','backend\DepartmentsController@showSubs')->name('showSubs');

    Route::get('show_adverts/{id}','backend\DepartmentsController@showAdverts')->name('showAdverts');



    Route::resource('products','backend\ProductController');
    Route::get('products/image/{id}','backend\ProductController@deleteSingleImage');


    Route::resource('advices','backend\AdviceController');

    Route::resource('brands','backend\BrandController');

    Route::resource('agencies','backend\AgencyController');

    Route::resource('privacy','backend\PraivacyController');

    Route::resource('policy','backend\PolicyController');

    Route::resource('shipping','backend\ShippingController');

    Route::resource('replacement','backend\ReplacementController');

    Route::resource('payment','backend\PaymentController');

    Route::resource('orders','backend\OrderController');
    Route::post('orders/makeSpecial/{id}','backend\OrderController@makeSpecial')->name('make_special');


    //vistores message
    Route::resource('visitorsMessages','backend\visitorMessageController');
    Route::get('sendmessage','backend\UserController@msgAll');
    Route::get('sendEmailMessage','backend\visitorMessageController@replyMsg');
    //about
    Route::get('/about' , 'Backend\AboutController@index')->name('about') ;
    Route::put('/about/{id}' , 'Backend\AboutController@update')->name('about_update') ;
    // privacies
    Route::get('privacies','backend\PrivaciesController@index')->name('privacies');
    Route::get('/privacies/{id}' , 'backend\PrivaciesController@update')->name('privacies_update') ;
    // social media  :
    Route::resource('social-media', 'Backend\SocialMediaController');
    // users
    Route::resource('users','backend\UserController');
    Route::post('/sendMsg/{id}','backend\UserController@postMsg');



});



Auth::routes();

app/Http/Controllers/backend/AboutController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\About ; 
use App\About_description ;
use App\About_photos ;
use App\Language ; 
use LaravelLocalization ; 
use DB ; 
use Auth ; 
use File ; 


class AboutController extends Controller
{
    
	/**
	 * So here we will check if we have about information 
	 * then we will update it unless create a new one  
	 * cause this is a single blade 
	 * @return [type] [description]
	 */
	public function index(){

	    $about = About::updateOrCreate(['id'=>1]);

	    $languages = Language::where(['status'=>'1'])->get();
	    foreach($languages as $language){

		    $about_description = About_description::updateOrCreate([

		    	'about_id'=>$about->id , 
		    	'language_id'=>$language->id
		    ]);
	    }
	//return $about->description;
	    return view('backend.about.index')->withAbout($about)->withLanguages($languages);
    }

    public function update(Request $request , $id){

         //   dd($request) ;

        $rules=[
            'phone'=>'required|' ,
            'email'=>'required|min:3|max:250',
            'ios_app'=>'required|min:3|max:250',
            'google_store'=>'required|min:3|max:250',
            
            'name_en'=>'required|min:3|max:250',
            'name_ar'=>'required|min:3|max:250',
            'desc_en'=>'required|min:3',
            'desc_en'=>'required|min:5',
            'address_en'=>'required|min:5',
            'address_ar'=>'required|min:3',



        ];

        $this->validate($request , $rules) ;
    	 
    	$about = About::find($id);


    	//$about->status = $request->status == 'on' ? 'active':'not_active' ;
    	$about->phone = $request->phone ;
    	$about->email = $request->email ;
    	$about->ios_app =$request->ios_app;
    	$about->google_store =$request->google_store;
        $about->save();

		if($request->image){

              $image= $request->file('image');
           
     $extension = $image->getClientOriginalExtension();

     $image_rename = str_random(6). '.' .$image->getClientOriginalExtension();


      $image->move(public_path('uploads/about/'), $image_rename) ;

                    $about->image = $image_rename ;
                    $about->save();


                }


 


            $descriptions = $about->description ; 

            // $slug =  new Slug ; 
            foreach ($descriptions as $description) {
                
                
                $description->about_id = $about->id ; 
                $description->language_id = $description->language_id ;


                $description->title = $request->input("name_".$description->language->label);
                $description->description = $request->input("desc_".$description->language->label);
                $description->address = $request->input("address_".$description->language->label);
                $description->why_do_i_need_it = $request->input("why_do_i_need_it_".$description->language->label);


                $description->save(); 
            }


             // flashing a success message  
           session()->flash('success' , trans('backend.about_info_updated'));

                
    			return back(); 

    }






}

app/Http/Controllers/backend/AdvertsController.php
<?php

namespace App\Http\Controllers\backend;

use App\Article;
use App\article_description;
use App\Article_image;
use App\Http\Controllers\Controller;
use App\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Validator;
use Storage ;
use File ;

class AdvertsController  extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $languages=Language::where('status','1')->get();
        $articles=Article::where('type','advert')->with('description')->get();
     //  return $articles;
        return view('backend.advert.index',compact('articles','languages'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $languages=Language::where('status','1')->get();

        return view('backend.advert.create',compact('languages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $rules=[
            "name_ar" => "required|min:3|max:255" ,
            "desc_ar" =>"required|min:5" ,
            "name_en" => "required|min:3|max:255",
            "desc_en" =>"required|min:3",
            "image" =>"image|required"
        ];

        $this->validate($request , $rules) ;

            $pic='';
            /** upload image ....... */
            if ($request->hasFile('image')) {
                $pic = $this->uploadImage($request->file('image'));
            }
            /**  create new doctor @var  $doctor  */
            $article=new Article();
            $article->addedBy_id=Auth::user()->id;
            $article->type='advert';
            $article->image=$pic;
            $article->save();


            $languages = Language::where('status','1')->get();

            foreach($languages as $language) {

                $articleDescription = new article_description();
                $articleDescription->article_id=$article->id;
                $articleDescription->language_id=$language->id;
                $articleDescription->type='advert';
                $articleDescription->name=$request->input("name_$language->label");
                $articleDescription->description= $request->input("desc_$language->label");
                $articleDescription->save();

            }

            session()->flash('success' , trans('backend.article_message_added'));
            return redirect()->route('advert.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        $languages=Language::where('status','1')->get();
        $adverts=Article::where(['type'=>'advert','id'=>$id])->with('description')->first();
      //  return $adverts;
        return view('backend.advert.show',compact('languages','adverts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $languages=Language::where('status','1')->get();
        $adverts=Article::where(['type'=>'advert','id'=>$id])->with('description.languages')->first();
      //return $adverts;
        return view('backend.advert.edit',compact('languages','adverts'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
      //return $id;

        $rules=[
            "name_ar" => "required|min:3|max:255" ,
            "desc_ar" =>"required|min:5" ,
            "name_en" => "required|min:3|max:255",
            "desc_en" =>"required|min:3",
            "image" =>"image|"
        ];

        $this->validate($request , $rules) ;

            $article=Article::find($id);
            
            /** upload image ....... */
            if ($request->hasFile('image')) {
                $pic = $this->uploadImage($request->file('image'));
                $article->image=$pic;
                $article->save();
            }



            $descriptions = $article->description;


        // return  $descriptions;
            // $slug =  new Slug ;
            foreach ($descriptions as $description) {


                $description->article_id = $article->id ;
                $description->language_id = $description->language_id ;

                if ($request->has("name_".$description->languages->label)) {
                    $description->name = $request->input("name_".$description->languages->label);
                }

                if ($request->has("desc_".$description->languages->label)) {

                    $description->description = $request->input("desc_".$description->languages->label);
                }

                $description->save();
            }

            session()->flash('success' , trans('backend.article_message_added'));
            return redirect()->route('advert.index');
        
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $doctor=Article::find($id);
        $image=$doctor->imageName;
        //delete old image...................
        $path = public_path().'/uploads/articles/'.$image;
        File::delete($path);
        Article::destroy($id);

        session()->flash('success' , trans('backend.articles_message_deleted'));
        return redirect()->route('advert.index');
    }

    public function uploadImage($image)
    {
        $fileName = $image->getClientOriginalName();
        $fileExtension = $image->getClientOriginalExtension();


        if ($image) {
            //rename uploaded file
            $new_image_name = md5(date("u") . rand(1, 1000) . uniqid('@@yas##_') .$fileName) . '.' .$fileExtension ;

            //move file
            $image->move(public_path('uploads/articles'), $new_image_name);

            return $new_image_name;
        }
        return null;
    }
}

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;

use App\Cart;
use App\Product;
use App\User;
use App\Brand;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $products=Product::get()->count();

       // $orders=Cart::get()->count();

        $users=User::get()->count();

       // $brands=Brand::get()->count();


        return view('backend.index',compact('products','users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/visitorsMessages/create.blade.php
@extends('backend.app')

@section('page_title' , trans('backend.languages'))

@section('breadcrumb')


         <li>
           <a href="{{route('visitorsMessages.index')}}">{{trans('backend.languages')}}</a>
            <i class="fa fa-circle"></i>
         </li>
         <li>
          <span class="active">{{trans('backend.add_language')}}</span>
         </li>


@endsection

@section('content')

<div class="portlet box blue">

   <div class="portlet-body">
      <div class="tabbable-custom nav-justified">
         <ul class="nav nav-tabs nav-justified">
            @foreach($languages as $lang)
            <li class="{{$loop->iteration == 1 ? 'active' : '' }}">
               <a href="#{{$lang->label}}" data-toggle="tab" aria-expanded="true"> {{strtoupper($lang->label)}}</a>
            </li>
            @endforeach
         </ul>
         <form action="{{route('languages.store')}}" method="post" id="form_sample_2" enctype="multipart/form-data">
         {{csrf_field()}}
            <div class="tab-content">
               @foreach($languages as $lang)
               <div class="tab-pane {{$loop->iteration == 1 ? 'active' : '' }} " id="{{$lang->label}}">

                  <div class="form-group form-md-line-input">
                     <input type="text" class="form-control" name="name_{{$lang->label}}" id="form_control_1" placeholder="{{trans('backend.language_name')}}">
                     <label for="form_control_1">{{trans('backend.language_name')}}
                     <span class="required">*</span>
                     </label>
                     <span class="help-block">{{trans('backend.language_name')}}</span>
                  </div>

                  <div class="form-group form-md-line-input">
                     <input type="text" class="form-control" name="label_{{$lang->label}}" placeholder="{{trans('backend.language_label')}}" id="form_control_1" >

                     <label for="form_control_1">{{trans('backend.language_label')}}
                     <span class="required">*</span>
                     </label>
                     <span class="help-block">{{trans('backend.language_label')}}</span>
                  </div>




               </div>
               @endforeach


               <div class="form-actions">

                  <div class="row">
                     <div class="col-md-12">
                        <button type="submit" class="btn green">{{trans('backend.save')}}</button>
                        <button type="reset" class="btn default">{{trans('backend.cancel')}}</button>
                     </div>
                  </div>
               </div>
            </div>
         </form>
      </div>
   </div>
</div>

@endsection

resources/views/backend/visitorsMessages/index.blade.php
@extends('backend.app')

@section('page_title' , trans('backend.visitors_messages'))

@section('breadcrumb')


         <li>
           <a href="{{route('visitorsMessages.index')}}">{{trans('backend.visitors_messages')}}</a>
            <i class="fa fa-circle"></i>
         </li>
         <li>
          <span class="active">{{trans('backend.visitors_messages')}}</span>
         </li>


@endsection



@section('extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
            <link href="{{Request::root()}}/backend/assets/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
            <link href="{{Request::root()}}/backend/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet" type="text/css" />
           {{--<link href="{{Request::root()}}/backend/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap-rtl.css" rel="stylesheet" type="text/css" />--}}

            <!-- END PAGE LEVEL PLUGINS -->

@endsection

@section('content')

 <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
                                <div class="portlet-title">
                                    <div class="caption font-dark">
                                        <i class="icon-settings font-dark"></i>
                                        <span class="caption-subject bold uppercase"> {{trans('backend.visitors_messages')}}</span>
                                    </div>

                                </div>
                                <div class="portlet-body">
                                    
                                    <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                                        <thead>
                                            <tr>

                                                <th>#</th>
                                                <th>{{trans('backend.name')}} </th>
                                                  <th>{{trans('backend.subject')}} </th>
                                                  <th>{{trans('backend.email')}} </th>
                                                  <th>{{trans('backend.message')}} </th>

                                                <th> {{trans('backend.added_date')}}  </th>
                                                <th> {{trans('backend.actions')}} </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                          @if($visitorsMessages->count()>0)

                                      		@foreach($visitorsMessages as $visitorsMessage)
                                            <tr class="odd gradeX">

                                                <td> {{ $loop->iteration }} </td>
                                                <td>
                                                   {{ $visitorsMessage->Name }}
                                                </td>
                                                 <td>
                                                   {{ $visitorsMessage->subject }}
                                                </td>
                                                 <td>
                                                   {{ $visitorsMessage->email }}
                                                </td>
                                                 <td>
                                                   {{ $visitorsMessage->message }}
                                                </td>


                                                <td>
                                                    {{--<span class="label label-sm label-success"> Approved </span>--}}
                                                  {{ date('Y-m-d' , strtotime($visitorsMessage->created_at)) }}
                                                </td>

                                                <td>
                                                    <div class="btn-group">
                                                 <a   class="tooltips"  href="{{ route('visitorsMessages.show' , $visitorsMessage->id) }}" data-toggle="tooltip" data-original-title="{{ trans('backend.show_message') }}">
                                                  <i class="fa fa-reply"></i> </a>

                                                        &nbsp;	&nbsp;  &nbsp;	&nbsp;

                                                        <a   class="tooltips"  onclick="$('.messages_form_{{$visitorsMessage->id}}').submit();" data-toggle="tooltip" data-original-title="{{ trans('backend.delete') }}"> <i class="fa fa-close text-danger"></i> </a>

                                                          {!! Form::open(['route'=>['visitorsMessages.destroy', $visitorsMessage->id] , 'class'=>"messages_form_$visitorsMessage->id" , 'method' =>'POST']) !!}

                                                           {!! method_field('DELETE') !!}


                                                           {!! Form::close() !!}

                                                    </div>
                                                </td>
                                            </tr>
                                            @endforeach
                          @endif
                                        </tbody>
                                    </table>
                                </div>
                            </div>
   <!-- END EXAMPLE TABLE PORTLET-->



@endsection

@section('extra_js')
<script src="{{Request::root()}}/backend/assets/global/scripts/datatable.js" type="text/javascript"></script>
        <script src="{{Request::root()}}/backend/assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
        <script src="{{Request::root()}}/backend/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="{{Request::root()}}/backend/assets/global/scripts/app.min.js" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
         <script src="{{Request::root()}}/backend/assets/pages/scripts/table-datatables-buttons.min.js" type="text/javascript"></script>


@endsection

resources/views/backend/visitorsMessages/show.blade.php
@extends('backend.app')

@section('page_title' , trans('backend.visitors_messages'))

@section('breadcrumb')


         <li>
           <a href="{{route('visitorsMessages.index')}}">{{trans('backend.visitors_messages')}}</a>
            <i class="fa fa-circle"></i>
         </li>
         <li>
          <span class="active">{{trans('backend.msg')}}</span>
         </li>


@endsection

@section('content')
    <div class="portlet box blue">

        <div class="portlet-body">
            <div class="tabbable-custom nav-justified">
                <ul class="nav nav-tabs nav-justified">

                        <li class="active">
                            <a href="#ar" data-toggle="tab" aria-expanded="true">{{trans('backend.msg')}}</a>
                        </li>

                </ul>

                    <div class="tab-content">

                            <div class="tab-pane active" id="ar">

                                

                                <div class="col-md-12">
                                    <!-- BEGIN Portlet PORTLET-->
                                    <div class="portlet light">
                                        <div class="portlet-title">
                                            <div class="caption">
                                                <i class="icon-paper-plane font-yellow-casablanca"></i>
                                                <span class="caption-subject bold font-yellow-casablanca uppercase"> {{trans('backend.msg')}} </span>
                                            </div>
                                           
                                        </div>
                                        <div class="portlet-body">
                                            <h1 class="font-green sbold uppercase">
                                                {{$visitorsMessage->Name}}
                                            </h1>
                                             <h3>
                                                 {{$visitorsMessage->email}}
                                             </h3>
                                            <p>
                                            <h3>{{trans('backend.msg')}}</h3>   {{$visitorsMessage->message}}
                                            </p>
                                        </div>
                                    </div>
                                    <!-- END Portlet PORTLET-->
                                </div>





                            </div>
                       


                        <div class="form-actions">

                            <div class="row">
                                <div class="col-md-12">
                                   
                                    <a  class="btn red" href="#form_modal2" data-toggle="modal" > {{trans('backend.reply')}}
                                        <i class="fa fa-reply"></i>
                                    </a>
                                </div>

                                <div id="form_modal2" class="modal fade" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                                <h4 class="modal-title">{{trans('backend.send_msg')}}</h4>
                                            </div>
                                            <div class="modal-body">
                                                <form action="{{url('sendEmailMessage')}}" method="get" class="form-horizontal">

                                                    <div class="form-group">
                                                        <label class="control-label col-md-4">{{trans('backend.msg')}}</label>
                                                        <div class="col-md-8">
                                                                <textarea name="message" class="form-control input-large" placeholder="{{trans('backend.enter_your_msg')}}" size="16" type="text" value="" >
                                                                </textarea>

                                                                <input type="hidden" name="email" value="{{$visitorsMessage->email}}">
                                                                <input type="hidden" name="name" value="{{$visitorsMessage->Name}}">

                                                        </div>
                                                    </div>




                                            </div>
                                            <div class="modal-footer">
                                                <button class="btn dark btn-outline" data-dismiss="modal" aria-hidden="true">{{trans('backend.close')}}</button>
                                                <button class="btn green" >{{trans('backend.send')}}</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </div>


@endsection