routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get ( '/redirect/{service}', 'Auth\RegisterController@redirect' );
Route::get ( '/callback/{service}', 'Auth\RegisterController@callback' );

Route::group(['prefix' => LaravelLocalization::setLocale() ], function()
{
    Route::post('register' , 'Auth\RegisterController@register');
    // login
    Route::post('loginUser' , 'Auth\LoginController@loginUser');
});


//-------------------------------------------------------------------//
//--------------------------ADMIN PANEL------------------------------//
//-------------------------------------------------------------------//

Route::group(['prefix' => LaravelLocalization::setLocale(),'middleware'=>['localeSessionRedirect', 'localizationRedirect', 'localeViewPath','web']],function() {
    
   Route::get('/', 'HomeController@index')->name('homepage');

   Route::get('/register', 'HomeController@register');
   Route::post('/registerform','HomeController@registerform');

   Route::get('loginpage','HomeController@loginpage');
   Route::post('loginform','HomeController@loginform');


   Route::get('/user_ads/{id}', 'HomeController@user_ads')->name('myadv');
   Route::get('/Favorits_ads', 'HomeController@Favorits_ads');
   Route::get('/category', 'HomeController@category');
   Route::get('/ad_details/{id}', 'HomeController@ad_details');

   Route::get('/advpage','HomeController@advpage');
   Route::post('/addadvert','HomeController@addadvert');

   Route::post('/contactus','HomeController@contactus');

   Route::get('/catadverts', 'HomeController@catadverts');

   Route::get('/catadvertsdetails/{id}','HomeController@catadvertsdetails');
   

   Route::post('/searchresult','HomeController@searchresult');
   


} );

  //-------------------------------------------------------------------//
 //--------------------------ADMIN PANEL------------------------------//
//-------------------------------------------------------------------//

Route::group(['prefix' => LaravelLocalization::setLocale(),'middleware'=>['localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ,'admin']],function() {

    Route::get('/adminPanel','backend\DashboardController@index')->name('adminPanel');


    Route::resource('languages','backend\LanguagesController');

    Route::resource('departments','backend\DepartmentsController');

    Route::post('add_sub/{id}','backend\DepartmentsController@addSub')->name('add_sub');
    Route::post('store_sub/{id}','backend\DepartmentsController@storeSub')->name('store_sub');

    Route::get('show_subs/{id}','backend\DepartmentsController@showSubs')->name('showSubs');

    Route::get('show_adverts/{id}','backend\DepartmentsController@showAdverts')->name('showAdverts');



    Route::resource('products','backend\ProductController');
    Route::get('products/image/{id}','backend\ProductController@deleteSingleImage');


    Route::resource('advices','backend\AdviceController');

    Route::resource('brands','backend\BrandController');

    Route::resource('agencies','backend\AgencyController');

    Route::resource('privacy','backend\PraivacyController');

    Route::resource('policy','backend\PolicyController');

    Route::resource('shipping','backend\ShippingController');

    Route::resource('replacement','backend\ReplacementController');

    Route::resource('payment','backend\PaymentController');

    Route::resource('orders','backend\OrderController');
    Route::post('orders/makeSpecial/{id}','backend\OrderController@makeSpecial')->name('make_special');


    //vistores message
    Route::resource('visitorsMessages','backend\visitorMessageController');
    Route::get('sendmessage','backend\UserController@msgAll');
    Route::get('sendEmailMessage','backend\visitorMessageController@replyMsg');
    //about
    Route::get('/about' , 'Backend\AboutController@index')->name('about') ;
    Route::put('/about/{id}' , 'Backend\AboutController@update')->name('about_update') ;
    // privacies
    Route::get('privacies','backend\PrivaciesController@index')->name('privacies');
    Route::get('/privacies/{id}' , 'backend\PrivaciesController@update')->name('privacies_update') ;
    // social media  :
    Route::resource('social-media', 'Backend\SocialMediaController');
    // users
    Route::resource('users','backend\UserController');
    Route::post('/sendMsg/{id}','backend\UserController@postMsg');



});



Auth::routes();

app/Agency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agency extends Model
{
    //

    public function description(){


        return $this->hasMany('App\AgencyDescription') ;
    }
}

app/Http/Controllers/backend/AboutController.php
<?php

namespace App\Http\Controllers\backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\About ; 
use App\About_description ;
use App\About_photos ;
use App\Language ; 
use LaravelLocalization ; 
use DB ; 
use Auth ; 
use File ; 


class AboutController extends Controller
{
    
	/**
	 * So here we will check if we have about information 
	 * then we will update it unless create a new one  
	 * cause this is a single blade 
	 * @return [type] [description]
	 */
	public function index(){

	    $about = About::updateOrCreate(['id'=>1]);

	    $languages = Language::where(['status'=>'1'])->get();
	    foreach($languages as $language){

		    $about_description = About_description::updateOrCreate([

		    	'about_id'=>$about->id , 
		    	'language_id'=>$language->id
		    ]);
	    }
	//return $about->description;
	    return view('backend.about.index')->withAbout($about)->withLanguages($languages);
    }

    public function update(Request $request , $id){

         //   dd($request) ;

        $rules=[
            'phone'=>'required|' ,
            'email'=>'required|min:3|max:250',
            'ios_app'=>'required|min:3|max:250',
            'google_store'=>'required|min:3|max:250',
            
            'name_en'=>'required|min:3|max:250',
            'name_ar'=>'required|min:3|max:250',
            'desc_en'=>'required|min:3',
            'desc_en'=>'required|min:5',
            'address_en'=>'required|min:5',
            'address_ar'=>'required|min:3',



        ];

        $this->validate($request , $rules) ;
    	 
    	$about = About::find($id);


    	//$about->status = $request->status == 'on' ? 'active':'not_active' ;
    	$about->phone = $request->phone ;
    	$about->email = $request->email ;
    	$about->ios_app =$request->ios_app;
    	$about->google_store =$request->google_store;
        $about->save();

		if($request->image){

              $image= $request->file('image');
           
     $extension = $image->getClientOriginalExtension();

     $image_rename = str_random(6). '.' .$image->getClientOriginalExtension();


      $image->move(public_path('uploads/about/'), $image_rename) ;

                    $about->image = $image_rename ;
                    $about->save();


                }


 


            $descriptions = $about->description ; 

            // $slug =  new Slug ; 
            foreach ($descriptions as $description) {
                
                
                $description->about_id = $about->id ; 
                $description->language_id = $description->language_id ;


                $description->title = $request->input("name_".$description->language->label);
                $description->description = $request->input("desc_".$description->language->label);
                $description->address = $request->input("address_".$description->language->label);
                $description->why_do_i_need_it = $request->input("why_do_i_need_it_".$description->language->label);


                $description->save(); 
            }


             // flashing a success message  
           session()->flash('success' , trans('backend.about_info_updated'));

                
    			return back(); 

    }






}

app/Http/Controllers/backend/AdvertsController.php
<?php

namespace App\Http\Controllers\backend;

use App\Article;
use App\article_description;
use App\Article_image;
use App\Http\Controllers\Controller;
use App\Language;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Validator;
use Storage ;
use File ;

class AdvertsController  extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $languages=Language::where('status','1')->get();
        $articles=Article::where('type','advert')->with('description')->get();
     //  return $articles;
        return view('backend.advert.index',compact('articles','languages'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $languages=Language::where('status','1')->get();

        return view('backend.advert.create',compact('languages'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

        $rules=[
            "name_ar" => "required|min:3|max:255" ,
            "desc_ar" =>"required|min:5" ,
            "name_en" => "required|min:3|max:255",
            "desc_en" =>"required|min:3",
            "image" =>"image|required"
        ];

        $this->validate($request , $rules) ;

            $pic='';
            /** upload image ....... */
            if ($request->hasFile('image')) {
                $pic = $this->uploadImage($request->file('image'));
            }
            /**  create new doctor @var  $doctor  */
            $article=new Article();
            $article->addedBy_id=Auth::user()->id;
            $article->type='advert';
            $article->image=$pic;
            $article->save();


            $languages = Language::where('status','1')->get();

            foreach($languages as $language) {

                $articleDescription = new article_description();
                $articleDescription->article_id=$article->id;
                $articleDescription->language_id=$language->id;
                $articleDescription->type='advert';
                $articleDescription->name=$request->input("name_$language->label");
                $articleDescription->description= $request->input("desc_$language->label");
                $articleDescription->save();

            }

            session()->flash('success' , trans('backend.article_message_added'));
            return redirect()->route('advert.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

        $languages=Language::where('status','1')->get();
        $adverts=Article::where(['type'=>'advert','id'=>$id])->with('description')->first();
      //  return $adverts;
        return view('backend.advert.show',compact('languages','adverts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $languages=Language::where('status','1')->get();
        $adverts=Article::where(['type'=>'advert','id'=>$id])->with('description.languages')->first();
      //return $adverts;
        return view('backend.advert.edit',compact('languages','adverts'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
      //return $id;

        $rules=[
            "name_ar" => "required|min:3|max:255" ,
            "desc_ar" =>"required|min:5" ,
            "name_en" => "required|min:3|max:255",
            "desc_en" =>"required|min:3",
            "image" =>"image|"
        ];

        $this->validate($request , $rules) ;

            $article=Article::find($id);
            
            /** upload image ....... */
            if ($request->hasFile('image')) {
                $pic = $this->uploadImage($request->file('image'));
                $article->image=$pic;
                $article->save();
            }



            $descriptions = $article->description;


        // return  $descriptions;
            // $slug =  new Slug ;
            foreach ($descriptions as $description) {


                $description->article_id = $article->id ;
                $description->language_id = $description->language_id ;

                if ($request->has("name_".$description->languages->label)) {
                    $description->name = $request->input("name_".$description->languages->label);
                }

                if ($request->has("desc_".$description->languages->label)) {

                    $description->description = $request->input("desc_".$description->languages->label);
                }

                $description->save();
            }

            session()->flash('success' , trans('backend.article_message_added'));
            return redirect()->route('advert.index');
        
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $doctor=Article::find($id);
        $image=$doctor->imageName;
        //delete old image...................
        $path = public_path().'/uploads/articles/'.$image;
        File::delete($path);
        Article::destroy($id);

        session()->flash('success' , trans('backend.articles_message_deleted'));
        return redirect()->route('advert.index');
    }

    public function uploadImage($image)
    {
        $fileName = $image->getClientOriginalName();
        $fileExtension = $image->getClientOriginalExtension();


        if ($image) {
            //rename uploaded file
            $new_image_name = md5(date("u") . rand(1, 1000) . uniqid('@@yas##_') .$fileName) . '.' .$fileExtension ;

            //move file
            $image->move(public_path('uploads/articles'), $new_image_name);

            return $new_image_name;
        }
        return null;
    }
}

app/Http/Controllers/backend/DashboardController.php
<?php

namespace App\Http\Controllers\backend;

use App\Cart;
use App\Product;
use App\User;
use App\Brand;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $products=Product::get()->count();

       // $orders=Cart::get()->count();

        $users=User::get()->count();

       // $brands=Brand::get()->count();


        return view('backend.index',compact('products','users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/agencies/create.blade.php
@extends('backend.app')

@section('page_title' ,trans('backend.agencies'))

@section('breadcrumb')


    <li>
        <a href="{{route('agencies.index')}}">{{trans('backend.agencies')}}</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span class="active">{{trans('backend.add_agency')}}</span>
    </li>


@endsection

@section('extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{Request::root()}}/backend/assets/global/plugins/dropzone/dropzone.min.css" rel="stylesheet" type="text/css" />
    <link href="{{Request::root()}}/backend/assets/global/plugins/dropzone/basic.min.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->

@endsection


@section('content')


    <div class="portlet box blue">

        <div class="portlet-body">
            <div class="tabbable-custom nav-justified">
                <ul class="nav nav-tabs nav-justified">
                    @foreach($languages as $lang)
                        <li class="{{$loop->iteration == 1 ? 'active' : '' }}">
                            <a href="#{{$lang->label}}" data-toggle="tab" aria-expanded="true"> {{strtoupper($lang->label)}}</a>
                        </li>
                    @endforeach
                </ul>
                <form action="{{route('agencies.store')}}" method="post" id="form_sample_2" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="tab-content">
                        @foreach($languages as $lang)


                            {{-- it send both of names ( ar , en ) --}}

                            <div class="tab-pane {{$loop->iteration == 1 ? 'active' : '' }} " id="{{$lang->label}}">

                                <div class="form-group form-md-line-input {{ $errors->has("name_$lang->label") ? ' has-error' : '' }}">
                                    <input type="text" class="form-control" name="name_{{$lang->label}}" id="form_control_1" >
                                    <label for="form_control_1">{{trans('backend.title')}}
                                        <span class="required">*</span>
                                    </label>
                                    @if ($errors->first("name_$lang->label"))
                                        <span class="help-block">
                                        <strong>{{ $errors->first("name_$lang->label") }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group form-md-line-input {{ $errors->has("desc_$lang->label") ? ' has-error' : '' }}">
                     <textarea type="text" class="form-control" name="desc_{{$lang->label}}" id="form_control_1" >
                     </textarea>
                                    <label for="form_control_1">{{trans('backend.description')}}
                                        <span class="required">*</span>
                                    </label>
                                    @if ($errors->first("desc_$lang->label"))
                                        <span class="help-block">
                                        <strong>{{ $errors->first("desc_$lang->label") }}</strong>
                                    </span>
                                    @endif
                                </div>



                            </div>
                        @endforeach
                        <div class="form-group {{ $errors->has("image") ? ' has-error' : '' }}">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                    <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="" /> </div>
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
                                <div>
                                                                        <span class="btn default btn-file">
                                                                            <span class="fileinput-new"> {{trans('backend.select_image')}} </span>
                                                                            <span class="fileinput-exists"> {{trans('backend.change_image')}} </span>
                                                                            <input type="file" name="image"> </span>

                                    @if ($errors->first("image"))
                                        <span class="help-block">
                                        <strong>{{ $errors->first("image") }}</strong>
                                    </span>
                                    @endif
                                    <a href="javascript:;" class="btn default fileinput-exists" data-dismiss="fileinput"> {{trans('backend.remove')}}</a>
                                </div>
                            </div>

                        </div>

                        <div class="form-actions">

                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn green">{{trans('backend.save')}}</button>
                                    <button type="reset" class="btn default">{{trans('backend.cancel')}}</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>



@endsection

resources/views/backend/agencies/edit.blade.php
@extends('backend.app')

@section('page_title' ,trans('backend.brands'))

@section('breadcrumb')


    <li>
        <a href="{{route('brands.index')}}">{{trans('backend.brands')}}</a>
        <i class="fa fa-circle"></i>
    </li>
    <li>
        <span class="active">{{trans('backend.update_brand')}}</span>
    </li>


@endsection

@section('extra_css')
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <link href="{{Request::root()}}/backend/assets/global/plugins/dropzone/dropzone.min.css" rel="stylesheet" type="text/css" />
    <link href="{{Request::root()}}/backend/assets/global/plugins/dropzone/basic.min.css" rel="stylesheet" type="text/css" />
    <!-- END PAGE LEVEL PLUGINS -->

@endsection


@section('content')


    <div class="portlet box blue">

        <div class="portlet-body">
            <div class="tabbable-custom nav-justified">
                <ul class="nav nav-tabs nav-justified">
                    @foreach($languages as $lang)
                        <li class="{{$loop->iteration == 1 ? 'active' : '' }}">
                            <a href="#{{$lang->label}}" data-toggle="tab" aria-expanded="true"> {{strtoupper($lang->label)}}</a>
                        </li>
                    @endforeach
                </ul>
                <form action="{{route('agencies.update',$advice->id)}})}}" method="post" id="form_sample_2" enctype="multipart/form-data">
                    {{csrf_field()}}
                    {!! method_field('put') !!}
                    <div class="tab-content">
                        @foreach($advice->description as $description)


                            {{-- it send both of names ( ar , en ) --}}

                            <div class="tab-pane {{$loop->iteration == 1 ? 'active' : '' }} " id="{{$description->language->label}}">

                                <div class="form-group form-md-line-input {{ $errors->has("name_$description->language->label") ? ' has-error' : '' }}">
                                    <input type="text" value="{{$description->title}}" class="form-control" name="name_{{$description->language->label}}" id="form_control_1" >
                                    <label for="form_control_1">{{trans('backend.title')}}
                                        <span class="required">*</span>
                                    </label>
                                    @if ($errors->first("name_$description->language->label"))
                                        <span class="help-block">
                                        <strong>{{ $errors->first("name_$description->language->label") }}</strong>
                                    </span>
                                    @endif
                                </div>

                                <div class="form-group form-md-line-input {{ $errors->has("desc_$description->language->label") ? ' has-error' : '' }}">
                                    <input type="text" value="{{$description->title}}" class="form-control" name="desc_{{$description->language->label}}" id="form_control_1" >
                                    </input>
                                    <label for="form_control_1">{{trans('backend.description')}}
                                        <span class="required">*</span>
                                    </label>
                                    @if ($errors->first("desc_$description->language->label"))
                                        <span class="help-block">
                                        <strong>{{ $errors->first("desc_$description->language->label") }}</strong>
                                    </span>
                                    @endif
                                </div>



                            </div>
                        @endforeach
                        <div class="form-group {{ $errors->has("image") ? ' has-error' : '' }}">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
                                    <img src="{{Request::root().'/uploads/agencies/'.$advice->image}}" alt="" /> </div>
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"> </div>
                                <div>
                                                                        <span class="btn default btn-file">
                                                                            <span class="fileinput-new"> {{trans('backend.select_image')}} </span>
                                                                            <span class="fileinput-exists"> {{trans('backend.change_image')}} </span>
                                                                            <input type="file" name="image"> </span>

                                    @if ($errors->first("image"))
                                        <span class="help-block">
                                        <strong>{{ $errors->first("image") }}</strong>
                                    </span>
                                    @endif
                                    <a href="javascript:;" class="btn default fileinput-exists" data-dismiss="fileinput"> {{trans('backend.remove')}}</a>
                                </div>
                            </div>

                        </div>

                        <div class="form-actions">

                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" class="btn green">{{trans('backend.save')}}</button>
                                    <button type="reset" class="btn default">{{trans('backend.cancel')}}</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>



@endsection